### ISSUE TITLE
Set fixed height for the scroll of the bib. 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-select#115]
## Is your feature request related to a problem? Please describe.

See the following issue for background on how this was discovered and the design work that was done. 

- https://github.com/AlaskaAirlines/auro-select/issues/66

There is also this issue that came in after this was created that we should also consider from a UX point of view and perhaps use the same solution for both use cases where we have a long list of options with auro-select.

- https://github.com/AlaskaAirlines/auro-select/issues/127

## Describe the solution you'd like

The design should be discussed as to how this solves the original issue that was submitted. A technical specification needs to be discussed with the team and exit criteria defined. 

AC:  
- When a user interacts with the the scroll bar the bib should not close.
- The bib can never be taller than the screen size.
- The bib will leave a little space at the bottom of the screen so it never looks cut off.
- The bib needs a min-height defined.
- We need to decide if we want to support specific sizes or whether the user can make it any size they want with css.

## Note for `finement.
The flight search team implemented the work around Geoff suggested for the currency converter.
https://www.alaskaair.com/search/results?A=1&O=sea&D=las&OD=2023-08-25&OT=Anytime&DD=2023-08-25&DT=Anytime&UPG=none

Scroll down to the bottom of the page and click on the currency converter in the fine print.

- With that implementation you can see that once we try to touch the scroll bar the select closes because we don't officially support this but that would also have to be considered. This issue below will address the bug portion of the feature request.
- https://github.com/AlaskaAirlines/auro-menu/issues/159

**Comment by blackfalcon** [comment]
Meeting is scheduled with the team for a feature tech'refinement discussion.

**Comment by jason-capsule42** [comment]
`When a user interacts with the the scroll bar the bib should not close.`

This should be removed from the AC. It is already implemented.

**Comment by jason-capsule42** [comment]
`The bib will leave a little space at the bottom of the screen so it never looks cut off.`

This should at a minimum include the top as well.

We may want to look at left and right padding as well. This portion of the change may need to be in auro-dropdown though. Since we would want consistent behavior between at minimum auro-select and auro-combobox.

**Comment by blackfalcon** [comment]
Post conversation it was agreed that this work is not priority and the thing to be done is to update the demo to illustrate how a user can simply use CSS to restrict height and auro-menu will naturally listen to this.

**Comment by jordanjones243** [comment]
Work was addressed in this PR:
- https://github.com/AlaskaAirlines/auro-select/pull/220
