### ISSUE TITLE
Auro-select drops error state, even when error condition is "true"

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/auro-select#120]
## Describe the bug

Given this code: 
![image](https://user-images.githubusercontent.com/25255197/196488017-3517b340-128c-46c1-8b0a-bfe2b36b7713.png)
You'll notice that the error={isTooManyPax}. We only accept 7 passengers total (just for background on the condition, not directly related to the bug). If we select 3 children, then 5 adults, the error state will occur. If we then select 5, 6, or 7 adult passengers, the error text we slot (also evaluated based on the isTooManyPax condition) remains, but the error state drops off, even if the condition has evaluated to true.

## To Reproduce

https://user-images.githubusercontent.com/25255197/196490687-c075d324-f734-47e4-92f3-73ab1f0dd535.mov

Also can be reproduced on the auro doc site:
https://auro.alaskaair.com/components/auro/select#gsc.tab=0
1. Scroll down to the error example
2. Select any option other than the default one
3. Error state falls off

This has been mitigated in our test environment, but it required that we write code to manually re-add the error state on select of an option, in addition to  the error={isTooManyPax}:
![image](https://user-images.githubusercontent.com/25255197/196491594-64b4fcc3-a7f4-41e1-acdd-a2fc38618777.png)

## Expected behavior

When the error condition evaluates to true, selecting the same option or another incorrect option persists the error styles.

## Desktop (please complete the following information):

 - OS: big sur
 - Browser chrome
 - Version 105

**Comment by blackfalcon** [comment]
This issue is in review.

**Comment by jason-capsule42** [comment]
This is a valid bug.

auro-select currently assumes that any successful select event from the nested auro-menu is a valid option and resets the error state.

auro-select should be updated to use our new improved validation logic that matches the html5 spec as has been done in other form elements. This would include handling that internal validation would never override a custom error state applied via the error attribute.

**Comment by blackfalcon** [comment]
The following feature update will address the following issue

- https://github.com/AlaskaAirlines/auro-select/issues/118

**Comment by braven112** [comment]
Build working example of auro select with custom validation that calculates based on an additional auro-input data value. And applies appropriate custom error validation see the passenger example on flight search.
