### ISSUE TITLE
Borders are not behaving properly in focus and error states in Safari

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-select#131]
## Describe the bug

The border corners of the element are not rounded in Safari when the element is in a focus or error state.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/select
1. Click on any example
1. See error

## Expected behavior

Border corners are rounded.

## Desktop (please complete the following information):

 - Browser: Safari

## Additional context

This is a bug for all of our form elements, refer to this initial ticket opened in `auro-input`:
- https://github.com/AlaskaAirlines/auro-input/pull/208

This needs to be updated in the dropdown component to fix this issue
- https://github.com/AlaskaAirlines/auro-dropdown/issues/249

**Comment by Patrick-Daly-AA** [comment]
Issue now occurs, but slightly differently.  We are now getting Box Shadow outside of our borders instead.  Further investigation will be needed.  Seems to be localized to just with Auro Select.

**Comment by Patrick-Daly-AA** [comment]
![image](https://github.com/AlaskaAirlines/auro-select/assets/128407248/d634ae62-1e2c-415d-b520-8cbb9d615b58)

**Comment by Patrick-Daly-AA** [comment]
Putting back up for investigating to see if this issue is still occurring in the beta branch

**Comment by jordanjones243** [comment]
This bug is still valid and has not been handled in the color theming changes.
