### ISSUE TITLE
Mobile auro-select design

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-select#148]
## Is your feature request related to a problem? Please describe.

There are usability issues with the current select on mobile.

Example:
https://github.com/AlaskaAirlines/auro-menu/issues/165

## Describe the solution you'd like

Design a mobile version of select.

- [ ] competitive analysis
- [ ] design exploration
- [ ] blueprint

## Resources
Check this Figma file to track progress: https://www.figma.com/file/kNKeoeej8IZIaF0Vb1Ap2y/2022-P%26E-Internship?node-id=353%3A2074&t=SGka6pNMmmxWy0IA-1

**Comment by blackfalcon** [comment]
@jdeeezzy and @leeejune are to schedule a meeting with engineers to validate the concept and address any engineering issues that need to be created.

**Comment by blackfalcon** [comment]
Mobiie review has been moved to next week due to scheduling conflicts.

**Comment by jdeeezzy** [comment]
Under went the blueprint review with devs and feedback was given. Adjustments to blueprint will be made and another blueprint review will be scheduled once changes are completed.
