### ISSUE TITLE
Upgrading from 2.8.5 causes strange UI issues

### ISSUE THREAD

**Issue by jessieiswise** [AlaskaAirlines/auro-select#178]
## Describe the bug

After upgrading our Auro-select package from 2.8.5 to 2.9.6 I noticed unexpected Ui behavior where upon selection, the Auro-select is inserting some sort of text into the dropdown field

## To Reproduce

1 use Auro select 2.9.x in a vue environment 
2 observe that the select behavior is not as intended

** or if you don't have a vue env **

1 contact Jess on teams 
2 Ask her to demo the issue
3 She will have a branch handy locally and will install the package at the specified version
4 Upon load of our web component, select a drop down option
5 Observe "Lit#" text in dropdown field
## Expected behavior
No extraneous text in dropdown fields

## Screenshots

<img width="723" alt="Screenshot 2024-02-26 at 5 30 21 PM" src="https://github.com/AlaskaAirlines/auro-select/assets/8884051/1751c67e-5c1d-4a99-a909-e33237ecff12">

## Desktop (please complete the following information):

 - OS: Mac
 - Browser safari and chrome
 - Version latest

**Comment by blackfalcon** [comment]
@jessieiswise in your test branch, can you install previous versions between `>2.8.5 <=2.9.5`? Possibly work backward, e.g. `npm i @aurodesignsystem/auro-select@2.9.5` and see if we can zero in the version that introduced this bug? 

What is clear is that, somehow, the HTML content that Lit uses to track nodes is being injected into the slot content.  See the screenshot from the Auro doc site. While this UI issue is NOT happening in the doc site or locally running the element demo, Lit still produces the HTML comments you are seeing. 

![Image](https://github.com/AlaskaAirlines/auro-select/assets/181089/ca0885b9-6a13-4c8f-8cab-67e5ee7b0e52)

The question is... why is this being injected into the slot? And why Vue? 🤔

**Comment by jessieiswise** [comment]
I'll dig into this next week!

**Comment by jessieiswise** [comment]
Looks like 2.9.0 is the offending version. possibly related to this commit? https://github.com/AlaskaAirlines/auro-select/commit/ddeedf815917e9297ca5544b5029accbfaf68ab8

**Comment by jessieiswise** [comment]
Code snippet:

<auro-select
                  ?hidden="${!this.canRetrieveBagFee}"
                  id="bagfee"
                  data-cy="bag-fee"
                  ?disabled=${!this.enabledPassengers?.get(passenger.nameNumber)
                    ?.isCurrentlySelected || !this.bagEnabled}
                  placeholder="${this.getDefaultOption(passenger.bagFees[0])}"
                  ${ref(this.bagFeeRef[i])}
                  @auroSelect-valueSet=${() => this.onSelectBagFee(i)}
                >
                  <span slot="label"
                    >${`${this.bagsAccordionText.PassengerBags.CheckedBagsLabel}
                ${passenger.firstName} ${passenger.lastName}`}</span
                  >
                  <auro-menu>
                    ${passenger.bagFees.map(
                      (bagfee, j) => html`
                        <auro-menuoption value="${j}" data-cy="fee-option">
                          ${j == 0
                            ? this.getDefaultOption(bagfee)
                            : this.getBagFeeOption(bagfee)}</auro-menuoption
                        >
                      `
                    )}
                  </auro-menu>
                </auro-select>

**Comment by jessieiswise** [comment]
Link to usage: https://github.com/Alaska-ECommerce/rtf-bags/blob/59f3c502dbbe2399e869b4c215f14d5c68ce7d0e/src/index.ts#L610
