### ISSUE TITLE
disabled styles do not match other disabled auro components

### ISSUE THREAD

**Issue by cynthiaricomendoza-alaskaair** [AlaskaAirlines/auro-select#185]
## Describe the bug

when the auro-select component is disabled, it has an opacity set to 0.7 causing it to not appear the same as auro-input and auro-combobox when they are also disabled.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/select and scroll to the disabled example
2. Inspect the disabled auro-select component
3. Observe `host([disabled])` has opacity set to 0.7
4. Go to https://auro.alaskaair.com/components/auro/input and scroll to the disabled example
5. Inspect the disabled auro-input component
6. Observe `host([disabled])` does not have an opacity set

## Expected behavior

If auro components support the disabled property and they are set to disabled, I would like to see the styles be consistent across all components.

## Screenshots

Here is an example of what the disabled auro-combobox, auro-select, and auro-input look like beside one another.

<img width="904" alt="Screenshot 2024-04-24 at 16 40 45" src="https://github.com/AlaskaAirlines/auro-select/assets/116121736/f8f2b10a-9c41-4eb0-9ed1-46d588070c0f">

## Desktop (please complete the following information):

 - OS: iOS
 - Browser: Chrome
 - Version: latest

## Smartphone (please complete the following information):

 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

## Additional context

When I uncheck the opacity style in the dev tools, auro-select now has the same disabled styling as auro-combobox and auro-input:
<img width="1480" alt="Screenshot 2024-04-24 at 17 17 45" src="https://github.com/AlaskaAirlines/auro-select/assets/116121736/0b31c733-1c20-4276-8c92-58ce3d17cc4b">

**Comment by Patrick-Daly-AA** [comment]
This will be fixed as part of our larger theming and token overhaul we are in progress on.

**Comment by cynthiaricomendoza-alaskaair** [comment]
thanks for the update @Patrick-Daly-AA! do you have an estimate on when that work will be complete?

**Comment by Patrick-Daly-AA** [comment]
@cynthiaricomendoza-alaskaair , We're expecting theming work for colors to be completed in early June at the latest.  If you need a fix sooner, let us know and we can either do a one-off fix for this, or can ensure that we cover this early in the theming release(s).
