### ISSUE TITLE
Auro Select's Dropdown displays wonky inside Auro Dialog

### ISSUE THREAD

**Issue by dkt2** [AlaskaAirlines/auro-select#187]
## Describe the bug

Putting an Auro Select inside an Auro Dialog seems to mess with the calculations used to display Auro Select's Dropdown

## To Reproduce

1. Create a component with an Auro Select inside an Auro Dialog
1. Click on the Auro Select
1. Scroll the Auro Dialog up-and-down
1. Auro Select's Dropdown moves up-and-down

## Expected behavior

A reasonably fixed position for Auro Select's Dropdown durable through scrolling events

## Screenshots

<img width="1020" alt="auro-select-inside-auro-dialog-1-2" src="https://github.com/AlaskaAirlines/auro-select/assets/16234891/ca76ed49-3875-4d47-b6a5-59905403e855">

https://github.com/AlaskaAirlines/auro-select/assets/16234891/d4265a3a-4880-4daf-a524-13fc250be17e

## Desktop (please complete the following information):

 - OS: Mac OS
 - Browser Chrome
 - Version 124.0.6367.119 (Official Build) (arm64)

**Comment by Patrick-Daly-AA** [comment]
from initial assessment, this issue will probably need a code change in Auro-Dropdown to fix

**Comment by dkt2** [comment]
@Patrick-Daly-AA would you know how long the fix would take? It is being used as part of our LMS so it is a high priority item for us

**Comment by Patrick-Daly-AA** [comment]
@dkt2 at the moment we aren't sure.  We have a chunk of work in our backlog to replace popperJS with the native PopOver implementation that is now supported across all our supported browsers.  We're looking to see how soon we will be able to get that work in, and if that will be too long we can fix this sooner.

Tagging @braven112 for visibility.

**Comment by Patrick-Daly-AA** [comment]
@dkt2 Our work to implement native popover is being tracked here: https://github.com/AlaskaAirlines/auro-popover/issues/71  It's third on our list of major priorities behind color theming and a new component called Multi-select.  This puts the change-over to Native Popover at least a month out.

Are there other workarounds that you can try in the mean time?  If not, please contact @braven112 and we can work to coordinate a one-off fix sooner.

**Comment by Dayna-A** [comment]
@braven112  we don't have a nice workaround that doesn't involve corrupting the designs... can you halp?
![](https://tenor.com/nJ9AWgdpyIT.gif)

**Comment by dkt2** [comment]
Hi @braven112 (cc @Patrick-Daly-AA @blackfalcon),

I found a similar problem with Auro DatePicker

https://github.com/AlaskaAirlines/auro-select/assets/16234891/43163163-f987-4266-bd1c-b414ca34d8c6

It seems like a highly related problem to the Auro Select

**Comment by braven112** [comment]
> Hi @braven112 (cc @Patrick-Daly-AA @blackfalcon),
> 
> I found a similar problem with Auro DatePicker
> 
>  Screen.Recording.2024-05-16.at.9.24.25.AM.mov 
> It seems like a highly related problem to the Auro Select

Thanks for the extra example.  We are pretty sure the issue is a conflict with auro-dropdown and auro-dialog. The positioning of auro-dialog seems to be overwriting the positioning for any component that has a dropdown.

This issue never appears when an auro-dropdown component is used directly on the page vs inside an auro-dialog.

**Comment by fajar-apri-alaska** [comment]
Hi team,

Ok, so tl:dr I have one "hacky" solution:
1. have `position: relative` applied to `auro-select` outer `div`
<img width="1440" alt="image" src="https://github.com/AlaskaAirlines/auro-select/assets/124668226/ecba22c7-d20d-4900-80da-65fcdaaa251d">

2. also apply `transform` value for the `.popover` class inside the `auro-dropdown` itself like so:

```
.popover {
  // the `!important` is needed to overwrite the computed value coming from the popperJS itself.
  transform: translate(0) !important;
}

```

This will result in acceptable behavior, I think.

https://github.com/AlaskaAirlines/auro-select/assets/124668226/9e8be6f1-e90d-47d4-bbd0-4553c0a7c4c8

But sadly, we can't apply above solution from the light DOM of the consumer apps itself. So updates on both components (`auro-select` and `auro-dropdown`) are needed for this temporary solution.
