### ISSUE TITLE
jsdoc/no-undefined-types

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-select#193]
# General Support Request

Warning in build: 

```
/src/auro/select/src/auro-select.js
  38:1  warning  The type 'auroSelect-ready' is undefined           jsdoc/no-undefined-types
  39:1  warning  The type 'auroSelect-valueSet' is undefined        jsdoc/no-undefined-types
  40:1  warning  The type 'auroFormElement-validated' is undefined  jsdoc/no-undefined-types
```

## Support request

Address undefined types

## Possible Solution

n/a

## Context

n/a

## Exit criteria

This issue can be closed once the warning have been addressed.

**Comment by jason-capsule42** [comment]
These errors are already resolved by a previous change
