### ISSUE TITLE
select menu appearing detached from select element

### ISSUE THREAD

**Issue by ethanwmiller** [AlaskaAirlines/auro-select#197]
## Describe the bug

When an `auro-select` component is used inside an `auro-dialog`, the select menu appears detached from the rest of the select component. I am using `auro-select` version 2.10.6. 

## To Reproduce

1. Create an `auro-dialog`
2. Put an `auro-select` with a menu inside the dialog
3. Open the select menu and see that its position is off

## Expected behavior

The expected behavior is for the select menu to stay attached to the select component itself.

## Screenshots
<img width="854" alt="Screen Shot 2024-07-24 at 11 07 32 AM" src="https://github.com/user-attachments/assets/3bdcfb7b-c56f-498c-8231-d10ca1f31f47">

<img width="826" alt="Screen Shot 2024-07-24 at 11 07 40 AM" src="https://github.com/user-attachments/assets/c2282b11-26dd-42bc-b48d-eec92ed5ccf5">

## Desktop (please complete the following information):

 - OS: mac
 - Browser: Firefox
 - Version: 128

## Smartphone (please complete the following information):

 N/A

## Additional context

I've installed `auro-select` via CDN, as well as the latest versions of the `design-tokens` and `webcorestylesheets` (also via CDN).

**Comment by Patrick-Daly-AA** [comment]
@ethanwmiller , do you have any more information you can provide?  Are there any work-arounds you could try?  If there are any, we might be able to implement them as an official solution.

**Comment by ethanwmiller** [comment]
@Patrick-Daly-AA I haven't been able to find any work-arounds. The only other information I forgot to include is that updating to the latest version of `auro-dialog` does not solve the issue; the select menu is still appearing detached from the select element. So I'm on the latest versions of auro-select and auro-dropdown, both installed via CDN.

Is there any other info specifically that you need? Are you able to reproduce the bug?

**Comment by ethanwmiller** [comment]
@Patrick-Daly-AA any updates on this? Let me know what other info you need, if any. Thanks

**Comment by Patrick-Daly-AA** [comment]
@ethanwmiller Last we had checked, we were not able to reproduce this issue.  @jordanjones243 will reach out to you so we can better see your environment where this issue is occurring.

**Comment by ethanwmiller** [comment]
Met with @jason-capsule42 and @jordanjones243 today on this. We determined that the issue only happens on the Firefox browser and is unique to the Lounge application somehow - on Chrome it's fine, and the Auro docs site works in Firefox too.

The theory is that something in our dependencies is messing up the component somehow. So the go-forward plan is to update all of our auro dependencies in the Lounge application and see if that fixes the problem. If updating all our auro dependencies still doesn't fix it, I'll reach back out about continuing to look for a solution.
