### ISSUE TITLE
Non-compliant ESM code references

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-select#212]
### Please verify the version of auro-select you have installed

@latest

### Please describe the bug

See the following code

https://github.com/AlaskaAirlines/auro-select/blob/db981f86eda457cf23125cdaa2c8cd9272538235/src/auro-select.js#L20

Import endpoint does not have syntax prefix causing consumer's build to break. 

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

Updated components should not break build pipelines. 

### What browsers are you seeing the problem on?

n/a

### Additional context

n/a

### Exit criteria

This issue can be closed once the incomplete code has been updated.

**Comment by jason-capsule42** [comment]
This issue was already addressed in this ticketed work: https://github.com/AlaskaAirlines/auro-select/issues/210
