### ISSUE TITLE
auro-select:  Dropdown list too narrow and expanding to full screen

### ISSUE THREAD

**Issue by dPopeAlaskaAir** [AlaskaAirlines/auro-select#216]
## Describe the bug

Select component has a couple of issues when it comes to laying out the options for the dropdown

- When there are many options, the screen scrolls.  See image
- When the control is narrow, the options list is also narrow

## To Reproduce

Code example:

```
<auro-select
    aria-label="Phone Code"
    class="xs:tw-col-span-2 sm:tw-col-span-3 md:tw-col-span-2 lg:tw-col-span-2"
    value="1"
>
    <span slot="label">Code</span>
    <auro-menu>
        <auro-menuoption value="1">United States/Canada (+1)</auro-menuoption>
        <auro-menuoption value="506">Costa Rica (+506)</auro-menuoption>
        <auro-menuoption value="52">Mexico (+52)</auro-menuoption>
        <auro-menuoption value="93">Afghanistan (+93)</auro-menuoption>
        <auro-menuoption value="355">Albania (+355)</auro-menuoption>
```

## Screenshots

![image](https://github.com/user-attachments/assets/55ad0ba5-9d15-44a9-a226-556c62fdd825)

## Desktop (please complete the following information):

 - OS: Sonoma 14.4
 - Browser Chrome 
 - Version 130.0.6723.59

**Comment by Patrick-Daly-AA** [comment]
I think we have parameters you can configure to address these issues.  We'll have an engineer reach out to you @dPopeAlaskaAir to talk
