### ISSUE TITLE
Auro Select: the select dropdown position is not anchored to the opener / trigger in Safari and Firefox browsers

### ISSUE THREAD

**Issue by mlilli** [AlaskaAirlines/auro-select#222]
## Describe the bug

When opening an auro-select the dropdown position is not anchored to the opener / trigger, and is vertically off by 64px in Safari and Firefox browsers. The dropdown is positioned as expected in Chrome and Edge browsers.

## To Reproduce

1. Go [here](https://auro.alaskaair.com/components/auro/select#gsc.tab=0) in a Safari or Firefox browser
2. Click on any select menu.
3. See error

## Expected behavior

The dropdown should be anchored to the opener / trigger.

## Screenshots

<img width="1024" alt="Screenshot Auro Demo" src="https://github.com/user-attachments/assets/8e0dd24c-3940-4d11-8e58-a49f5129ef87">

<img width="460" alt="Screenshot Mobile App" src="https://github.com/user-attachments/assets/631241cc-5df8-466f-999d-8503158c68b0">

## Desktop (please complete the following information):

 - OS: Windows and macOS
 - Browser: Safari and Firefox
 - Version: all

## Smartphone (please complete the following information):

 - Device: iPhone and iPad
 - OS: all
 - Browser: stock browser, Safari, native app embedded web view
 - Version: all

## Additional context

This affects alaskaair.com production website and native web app (embedded web view). On small viewports / mobile devices, this prevents users from selecting the "MVP Gold 100k" and "MVP Gold Guest" options from the "Upgrade Type" select.

Repo: https://github.com/Alaska-ECommerce/flightsearch-lem-svelte/

**Comment by diana-dipalma** [comment]
Please note, this is impacting more than just Gold Guest upgrades. Several iPhone 16 users are now reporting that Gold 100k is unavailable as well. 

![Image (9)](https://github.com/user-attachments/assets/14f6c560-ca56-458d-90a9-4fc039028450)
