### ISSUE TITLE
Error state should not be cleared with required flag errors just because a value was added

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-select#42]
There may be a larger reason for this to have an error state. Since we don't control when the error flag is added we probably shouldn't assume that simply defining a value removes the error.

**Comment by blackfalcon** [comment]
This UX is consistent with how auro-input works, https://auro.alaskaair.com/components/auro/input

When an error is triggered, a user can come back and interact with that UI again and the error is removed. It is after this interaction that the state of the data will be again evaluated by either the client with code created by the consumer or with a page return post submission.
