### ISSUE TITLE
Docsite api demo page 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-select#48]
## Describe the bug

While the api demo pages works as expected in the local examples.html page, the same page when rendered on the docsite the UI breaks. 

The sample code is not within the scope of the accordion. 

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/select/api
1. See error

## Expected behavior

Example code is INSIDE the accordion.

**Comment by Patrick-Daly-AA** [comment]
It appears this issue is fixed.  @blackfalcon please confirm.
