### ISSUE TITLE
Select is showing highlighted text in trigger

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-select#52]
## Describe the bug

This was discovered on a mobile device. The issue is that on a mobile device only, the text inside a trigger is highlighted. This does not happen on a desktop browser in mobile mode. 

It is assumed that this is a default styling issue with iOS as the trigger in these examples are using button elements. 

<img width="564" alt="Screen Shot 2022-03-15 at 10 11 16 AM" src="https://user-images.githubusercontent.com/181089/158619738-c8e08714-8c63-4a6e-8560-6af9459eb015.png">
<img width="408" alt="Screen Shot 2022-03-15 at 10 12 04 AM" src="https://user-images.githubusercontent.com/181089/158619749-3673190c-e2f0-491c-b90d-37fac117bd93.png">

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/select ON A MOBILE DEVICE
1. Look at the demo
1. See error

## Expected behavior

Content in the trigger SHOULD NOT be highlighted. 

## Desktop (please complete the following information):

 - OS: macOS
 - Browser chrome
 - Version [current]

## Smartphone (please complete the following information):

 - Device: iPhone 12max
 - OS: current iOS
 - Browser safari

**Comment by jason-capsule42** [comment]
No longer an issue after latest API refactor.
