### ISSUE TITLE
On mobile devices, auro-select only closes when it loses focus, not on select.

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-select#53]
## Describe the bug
The auro-select doesn't close until it loses focus on mobile devices

## To Reproduce
![mobile-select](https://user-images.githubusercontent.com/10947475/159556634-99334aff-e7b4-481c-8632-2d8b6a6a212f.gif)

1. Open Chrome's mobile emulator (it also repros on actual mobile devices, we tried it on android)
2. Open the auro-select
3. Select an item
4. Notice the menu doesn't close

## Expected behavior

The menu should close on select. Unless this in fact _is_ the expected behavior?

**Comment by jason-capsule42** [comment]
No longer an issue after latest API refactor.
