### ISSUE TITLE
auro-select console error on doc site.

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-select#55]
## Describe the bug

Error in the console:
![image](https://user-images.githubusercontent.com/5118118/160468848-1cd98f7e-0598-4f27-9726-33f3db586e4e.png)

## To Reproduce

1. Go to '
https://auro.alaskaair.com/components/auro/select'
1. Inspect console '....'
1. See error

**Comment by blackfalcon** [comment]
The docsite is pulling the same utils.js file as the demo, but for some reason, this is not working in the docsite. 

I thought I made an issue about this, but that's the cause.

**Comment by jason-capsule42** [comment]
Actually the error is that the API for menu and selectedOption was changed to not pass the value with the event but select is still expecting it. I'll put a fix up for this shortly.
