### ISSUE TITLE
Providing an initial value for Auro-select causes the span not to be populated until first click

### ISSUE THREAD

**Issue by trafton** [AlaskaAirlines/auro-select#60]
When setting up and using the Auro-select component, we sometimes already have a value that has been previously selected and we would like to show this. Providing that value via the "value" prop at launch time causes the UI to render an empty span because the component has a value in this.value, but this.displayValue is undefined because it is set when the component receives a "selectedOption" event from Auro-menu.

## To Reproduce

1. Setup Auro-select as recommended in the API. 
2.  Do not provide a value in the "value" prop and notice that 'Please select option' is rendered, much like the examples in the API docs.
3. Provide a value in the "value" prop.
4. Now notice that when you load the page for the first time, you will notice an empty span until you select another option. 

Issue can be tracked down to this line where Auro-select decides to render the placeholder or not. https://github.com/AlaskaAirlines/auro-select/blob/5a996aa885231f693487687b304abef90aa0e747/src/auro-select.js#L159

## Expected behavior

When provided a value in the "value" prop, Auro-select should display that value without needing to interact with it first.

## Screenshots

<img width="1154" alt="Screen Shot 2022-03-30 at 4 58 13 PM" src="https://user-images.githubusercontent.com/1517922/160949925-94aeb25b-8549-431e-b314-ec69643b757e.png">

**Comment by blackfalcon** [comment]
@trafton can you confirm which version of auro-select you are using?
