### ISSUE TITLE
Click handler doesn't fire on inner `auro-menuoption`

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-select#61]
## Describe the bug
My click handler on the inner `auro-menuoption` tag doesn't fire when inside `auro-select` in  auro-select version 2.2.0

## To Reproduce
Put an `auro-menuoption` tag inside an `auro-select`, put an `onClick` handler on the `auro-menuoption` and see that my breakpoint is never hit. See below.

![countries-dropdown](https://user-images.githubusercontent.com/10947475/160952929-62732896-93c4-41a9-973b-3a8be3ad6bd6.gif)

To do a test, I put an `auro-menuoption` tag outside of `auro-select` and put a click handler on it. You can see it fire successfully in the screen cap below

![auro-menuoption](https://user-images.githubusercontent.com/10947475/160953315-559d3c4b-1c89-4965-a6a9-5e7eec5a2948.gif)

## Expected behavior

Click handler should capture the click event on the auro-menuoption inside the `auro-select`

## Desktop (please complete the following information):

 - Browser chrome

**Comment by DZwell** [comment]
Interestingly, `onMouseDown` _does_ work. I suppose I could just use that 🤷‍♂️

**Comment by blackfalcon** [comment]
@DZwell I am assuming that you were watching for the `click` event? 

Yes... this could probably be changed. Initially, there was a desire to have the checkmark show up with the initial click, e.g. mouse down, versus the click event which wouldn't apply the checkmark until the mouse was released. 

This isn't the case anymore as the experience is more directly tied to how the select menu closes right after the click and the applied checkmark is not seen until the select menu is opened again. 

@jason-capsule42 you have an opinion on this?

**Comment by jason-capsule42** [comment]
@DZwell I'm looking at the code in your samples above and it appears to me that you are essentially trying to bypass the built in API for detecting when an option is selected by attaching a secondary click handler onto the `auro-menuoption`.

I suggest using the APIs `selectedOption` event rather than attach the additional click handler.

```js
const stateSelect = document.querySelector('auro-select#stateSelect');

stateSelect.addEventListener('selectedOption', () => {
  console.warn('Value selected:', stateSelect.optionSelected.value);
});
```

Doing so means that the click handler on each menuoption is unnecessary, just listen for the auro-select to notify of the selection change.

Please let me know if that does not solve your needs.

**Comment by jason-capsule42** [comment]
Any work to better handle additional event handlers on menuoptions will be done as part of `auro-menu`. https://github.com/AlaskaAirlines/auro-menu/issues/123
