### ISSUE TITLE
Introduce error message prop

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-select#65]
## Is your feature request related to a problem? Please describe.

`auro-select` supports an error state with a red border, but does not support displaying an error message. In my application I need to show an error associated with a select, e.g. "Please select an option"

## Describe the solution you'd like

Introduce a prop so that an error message can be displayed.

## Describe alternatives you've considered

Handle showing the error message in my application code, e.g.

```lang-svelte
<auro-select error={showError}>
    <!-- truncated for readability -->
</auro-select>
{#if showError}
    <p class="errorText">{error}</p>
{/if}
```

Though this solution is not properly associated with the select using `aria-describedby`. An solution inside the component would make that easier.

## Additional context

Prior art in `auro-input`:

![image](https://user-images.githubusercontent.com/4992896/164814086-2d3596c7-ab5c-4f5d-b7b9-6d4216b3f78c.png)

**Comment by blackfalcon** [comment]
@leeejune I am not finding the error state for this element in the blueprints? https://www.figma.com/file/nyXRAgG4YzZaGdIVmPwARP/Select?node-id=322%3A298

Is this defined?

**Comment by blackfalcon** [comment]
Not sure yet to define this as a bug or a new feature.

**Comment by leeejune** [comment]
Since it uses input, I didn't display the other states; I assumed that it would inherit all of input's states... should I display all of the states?

**Comment by blackfalcon** [comment]
Closing issue in favor of new feature work

- https://github.com/AlaskaAirlines/auro-select/issues/118
