### ISSUE TITLE
Select Label must functionally work like Input Label

### ISSUE THREAD

**Issue by jpalmer108** [AlaskaAirlines/auro-select#71]
## Is your feature request related to a problem? Please describe.

The select input field is disjointed with the traditional text input fields. When used side-by-side on a customer form, the form doesn't look cohesive. We need our labels to work just like the input labels in order to make our form views more understandable for our customers. 

<img width="419" alt="Screen Shot 2022-05-04 at 2 56 16 PM" src="https://user-images.githubusercontent.com/102994201/166967281-0f7e6cbc-1e0b-4073-8457-ba3e24d117a3.png">

## Describe the solution you'd like

As a user, I want to see the Label large on the select field (with label color formatting), and upon selection of a menu option, I'd like the label to shrink above the selected menu option and clearly shown what's been, so that I can see clearly the label of the field and understand the relevance of my selected option by still seeing the label. 

Attached are DOM manipulated screenshots illustrating the concept of the desired flow:
 
<img width="332" alt="Screen Shot 2022-05-04 at 2 47 57 PM" src="https://user-images.githubusercontent.com/102994201/166831414-4ecc637f-d4b9-491a-9ab1-12373a7121eb.png">
<img width="338" alt="Screen Shot 2022-05-04 at 2 48 03 PM" src="https://user-images.githubusercontent.com/102994201/166831496-4a17881b-e53d-48ec-aff2-95764f6cd42f.png">
<img width="347" alt="Screen Shot 2022-05-04 at 2 48 48 PM" src="https://user-images.githubusercontent.com/102994201/166831415-1f0133f0-94a3-4ce3-b7ba-47550746f73e.png">

## Describe alternatives you've considered

I've attempted to use the label component currently implemented, however a placeholder is automatically added when I use that. When attempting to remove the placeholder, the label is still minified to the top of the screen. 

## Additional context
https://auro-prod-site-w2.azurewebsites.net/components/auro/select/api#label
Helptext label on documentation is a broken link

**Comment by blackfalcon** [comment]
Issue related to broken link has been moved to https://github.com/AlaskaAirlines/auro-select/issues/72

**Comment by jpalmer108** [comment]
Followed up with @jason-capsule42 to solidify some understanding behind the purpose and use of `helptext`. Realized my understanding of what the `helptext` slot is was entirely different than what it actually was; The confusion stemmed from my unfamiliarity with Auro, and a bug in the documentation on the `helptext` feature (code uses `helpertext`, not `helptext`). 

All that being said, I removed the `helptext` comments in my ticket to solidify issue clarity.

**Comment by leeejune** [comment]
https://github.com/AlaskaAirlines/auro-dropdown/issues/121

This issue should also fix the visual discrepancies. The intended behavior is that the dropdown only has label text when there is no value selected (default state). Unless the dev uses placeholder text AND label text, the dropdown would look and behave the same way input does.
