### ISSUE TITLE
Broken link in API docs page

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-select#72]
## Describe the bug

https://auro.alaskaair.com/components/auro/select/api#helpText

The link to the `helpText` part of the API example is broken. 

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/select/api
1. Click on `helpText`
1. See error

## Expected behavior

Link to scroll page

**Comment by jpalmer108** [comment]
Not sure if this is worth mentioning here or not, but @jason-capsule42 and I discovered the codeblock under the `helptext` api explanation also has a bug in the code. 

It uses `helpertext`, not `helptext`, and so the actual functionality of `helptext` is not demonstrated.

**Comment by jdeeezzy** [comment]
@jason-capsule42 it looks like this has been fixed. Can you confirm?

**Comment by blackfalcon** [comment]
This appears to have been address on May 10th with this commit 

- https://github.com/AlaskaAirlines/auro-select/commit/c64080310b9f10a4613d9f7755643c3efff0bf2f
