### ISSUE TITLE
Keyboard interaction: have up and down arrows change selection when dropdown is collapsed

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-select#73]
## Is your feature request related to a problem? Please describe.

With a native `<select>`, I can change the selected option by focusing the select and hitting the up and down arrows, even if the select is collapsed. I do this frequently with selects and it's an expected interaction for me.

## Describe the solution you'd like

`<auro-select>` should support the same interaction.

## Describe alternatives you've considered

n/a

## Additional context

GIF of interaction in a regular `<select>` (from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select))
![select-arrow](https://user-images.githubusercontent.com/4992896/168401862-6c137473-e9eb-4e02-a1c8-9ae1d778e11a.gif)

**Comment by blackfalcon** [comment]
this issue is being discussed here 

- https://github.com/AlaskaAirlines/WC-Generator/discussions/453
