### ISSUE TITLE
Make the height of auro-select the same as auro-input

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-select#81]
## Is your feature request related to a problem? Please describe.

When using auro-select as part of a form, the height discrepancy between the two is jarring.

## Describe the solution you'd like

Can we add a prop to pass in a custom size?

## Describe alternatives you've considered

I could probably dig in to the shadow root and modify the underlying elements but that seems less than ideal.

## Additional context

Here's a screenshot of the mockup we're working against:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/10947475/181391411-8ac3a9ff-90f6-4f1b-bb89-d391a655688b.png">

Here's what it looks like in our UI:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/10947475/181391547-59749f5e-c2e9-4c21-9190-97aa14471285.png">

You can see that the actual height of the element itself is the same as auro-input, but the bordered part of the select is less than that: 
<img width="790" alt="image" src="https://user-images.githubusercontent.com/10947475/181391646-c4e8b084-0fba-4cea-b41e-8dc3428b9016.png">

**Comment by braven112** [comment]
@leeejune let's double check this tomorrow and see what the correct height should be for these so they work well together.

**Comment by braven112** [comment]
I would recommend adding a label to select and then we'll need to address this issue #71 so that input and select can work together better.

We'll also reach out to the designer so we can sync on how to handle these going forward.

**Comment by leeejune** [comment]
Two things are missing:
### The label animation
- The label should shift up when the dropdown is triggered/filled for label=true, placeholder=false
- There should be options for when:
   - `label=true, placeholder=true` (does not need animation)
   - `label=true, placeholder=false` (need animation)
   - `label=false, placeholder=true` (missing this option, need animation)
@jason-capsule42 after our discussion and I found that there are no accessibility requirements for having a label on dropdown. 

### Spacing
The dropdown without either a label or placeholder should have larger spacing to have the same height as when there is both a label and placeholder text. See image below for correct UI, and refer to the [blueprint](https://www.figma.com/file/3TQhiKjQqQOKYqaqcO1zj2/Dropdown?node-id=906%3A753) for exact design tokens.
![image](https://user-images.githubusercontent.com/55998746/182132438-1629c177-1666-438a-a61f-d13c981187e5.png)

These things will fix issue #71 and the issue in the `auro-dropdown` repo [#121](https://github.com/AlaskaAirlines/auro-dropdown/issues/121).

**Comment by braven112** [comment]
During refinement we noticed that it is 66px and it should be 58px including the border.

AC: Validate that combobox, select, input and datepicker all are exactly the same height.

**Comment by blackfalcon** [comment]
Recatorigized this as a `bug` as the height consistency between elements needs to be fixed. No new feature to be added.
