### ISSUE TITLE
Allow auro-select to be reset

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-select#82]
## Is your feature request related to a problem? Please describe.

I need the ability to programmatically reset an auro-menu (really, an auro-select) so that the placeholder text shows back up and the value is cleared

## Describe the solution you'd like

I'll let @jason-capsule42 figure this one out 😉

## Additional context
This is my auro-select:

![image](https://user-images.githubusercontent.com/10947475/181811613-5b767f0e-5afd-4167-99f3-72bf0365240b.png)

After selecting an item I have no way of resetting it back to its initial state:
![image](https://user-images.githubusercontent.com/10947475/181811658-041c6135-cdf2-467f-9ac6-77f06b75b31a.png)

Merely finding the element and setting its value to `undefined` doesn't help.

**Comment by DZwell** [comment]
I’ve not been able to find a workaround for this, unfortunately. But I wouldn’t say I’m blocked by this yet as my work isn’t going out to prod at this sprint. Hopefully that helps prioritize, let me know if you need more info. I can keep you in the loop in terms of when we’re planning on releasing the work that depends on this.

**Comment by DZwell** [comment]
Hey @blackfalcon, had sprint planning today and we're hoping to release this in the next sprint or two, not sure how that works out with your priorities. Let me know if you need anything from me.

**Comment by blackfalcon** [comment]
@DZwell the focus for the next few sprints will be around dropdown-related elements. Please follow up with @jason-capsule42 for any specific details as he will most likely be doing the work.
