### ISSUE TITLE
Allow user to select more than 1 option (multi-select)

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-select#83]
## Is your feature request related to a problem?
As a user, I am using the auro-select as part of a Search UI. The auro-select will provide a list of available choices to choose from, but I would like to select 1 or more choices.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/3304352/182217516-d017c3ff-a45b-41f8-af98-32833ced2ebe.png)

## Describe alternatives you've considered

Make our own UI using a combination of auro-menu and something else.

## Additional context

none

**Comment by braven112** [comment]
@jordanchang This is a cool idea.  I would start with having your Designer reach out to @leeejune  to see if we have anything like this designed yet.

**Comment by blackfalcon** [comment]
@jordanchang this has been discussed with the team and there are various explorations within the UI designer group looking at multiple variations of this concept with Auro interactive form element. 

We are choosing to close this specific issue you created, but this is not the end of this story. Look for future updates.
