### ISSUE TITLE
Prevent icons in label span from opening dropdown

### ISSUE THREAD

**Issue by arrenkhl** [AlaskaAirlines/auro-select#85]
## Is your feature request related to a problem? Please describe.

The flight search team is rebuilding the planbook with Auro components, and this includes replacing the "Upgrade type" dropdown with auro-select as such:

Old planbook:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/43892293/183782699-a552d71b-b8f5-4c17-9a85-1fd7476bbed7.png">

New planbook:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/43892293/183782764-a367d71e-78bf-450d-b3af-c5ff895453fb.png">

We are able to open a drawer when clicking on the "?" icon, but doing so also opens the dropdown unintentionally:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/43892293/183783179-15c6293c-4f02-49d7-bee8-3af65a29653b.png">

## Describe the solution you'd like

Possible solutions that could address this problem:
- Setting a higher z-index on the label slot to prevent the dropdown from opening when the label is clicked
- An attribute that allows for the toggling of the above solution

## Describe alternatives you've considered

- Giving a higher z-index to the label span and icon
- Using the hide method on the auro-dropdown within auro-select's shadow root when the icon is clicked

## Additional context

This feature would also be needed in auro-dropdown to implement a similar clickable "?" icon in the label span when selecting the number of children in the planbook:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/43892293/183784460-5000ab66-5a74-4753-8a65-541bf585011e.png">

**Comment by jesussilverioea** [comment]
Thanks for opening this issue Arren. I am working with the auro-dropdown as fore-mentioned I would like this functionality as well on the auro-dropdown.

**Comment by braven112** [comment]
Thanks for submitting this.  It looks like these might have some UX issues on mobile devices at the very least if we have clickable icons inside the select and may also have some A11Y issues. We can reachout to @erikalanghauser or Bridget and get their thoughts and potentially come up with alternatives.

**Comment by braven112** [comment]
Talked with @erikalanghauser and @bridgetglewis.   Rather than adding this feature they'll come up with another option to allow users to select the icon to open the auro-drawer
