### ISSUE TITLE
Support auro-menu optional checkmark

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-select#88]
## Is your feature request related to a problem? Please describe.

Auro-menu now supports an optional checkmark. Per design the, default to no checkmark but keep it optional in auro-select.

## Describe the solution you'd like

Default to no checkmark, add a `checkmark` attribute that returns it.

**Comment by jordanjones243** [comment]
After further discussion, select will default to `checkmark`, but be reversed when `nocheckmark` is present in the `auro-menu`.
