### ISSUE TITLE
a11y: options are not re-read as a user moves through options.

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/auro-select#97]
## Describe the bug
When a user expands the auro-select, the options are read, but when they use the arrow keys to move through the different options, they aren't being re-read. Additionally, the navigation to the different options doesn't conform to the controls that the screen reader expects (at least for VoiceOver).

https://dev.azure.com/itsals/E_Sell_Shop/_boards/board/t/E_Sell_Shopping_Experience%20team/Stories/?workitem=774878
## To Reproduce

1. Go to [FS Microsite](https://www.alaskaair.com/search-qa/results?A=1&O=sea&D=lax&OD=2022-10-21&OT=Anytime&RT=false)
2. Navigate to the "sort by stops" drop down. It registers as a button, and after expanded instructs the user to use ctrl + option + shift + down to navigate through the list. It will highlight the first option, and then get stuck, unable to navigate further in the group.
3. When moving through the options with only the arrow keys, it is highlighting the other options, but it does not read them.

## Expected behavior

When a guest is navigating with a screen reader (VoiceOver, at least), the selection instructions that the screen reader tech gives work (if possible) and/or: when using only the arrow keys to navigate, the options read out loud on each option change (this is how current drop downs behave in ascom)

## Screenshots
When expanding, it will read each option, but it will not read them aloud as a user moves to each one with the arrow keys.
![image](https://user-images.githubusercontent.com/25255197/188738029-b6af7661-bd0a-4df5-b17e-d8e103761b91.png)

## Desktop (please complete the following information):

 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 104.x

**Comment by aesthetiques** [comment]
@blackfalcon 
So I found that if you use the VO commands to get into the control set:
1. Use VO + Arrow key until it highlights the trigger: 
![image](https://user-images.githubusercontent.com/25255197/188972835-b45d50d0-9e44-46d4-8167-5479ec4a39de.png)

2. When hovering the trigger, hit VO + space to expand it:
![image](https://user-images.githubusercontent.com/25255197/188972999-a886ffda-1871-41f5-b5dd-ed1701b5df0d.png)

3. VO + right arrow to highlight the drop down
![image](https://user-images.githubusercontent.com/25255197/188973403-595866c5-f31d-4fa8-b4bf-6bc4e7341246.png)
NOTE: You can use arrow up and down to navigate through the list from here, and it will select, but not read aloud.
SIDE NOTE  at bottom for additional bug(?) at this step

4. VO + shift + down to access the group

5. VO + any arrow key to navigate through, and it will read out the results.
6. Using space, enter, or VO + space will not select an option here. NOTE: If you've been also using arrow key (without voice over key bind) navigation here it will sometimes work with spacebar or enter key, but if you back out and re-enter, and attempt to select with VO + arrow key and NO arrow key by itself, it will not select an option when using space/enter/VO + space.


STEP 3 ADDITIONAL BUG:
:When moving thru the options here with arrow keys, it will alternate through the options while Voice Over is being used:
![image](https://user-images.githubusercontent.com/25255197/188973678-887ee0eb-bd74-492a-bfb3-7e56a06efb60.png)

**Comment by blackfalcon** [comment]
Validated. While this is keyboard accessible, there are issues with the VO for sure. Thanks for the feedback, we will review this and plan for a fix ASAP.

**Comment by blackfalcon** [comment]
FYI... this was validated in the Auro docsite. There is no need to specifically target the FS example to resolve this issue.
